### ISSUE TITLE
Is intkey-go code done?

### ISSUE THREAD

**Issue by Kaixinguoer210** [hyperledger/sawtooth-sdk-go#16]
I have understood **intkey-python** code  in **sawtooth-core** project. After that, I glance over **intkey-go** code in this project and I don't know where I can find those code which is used to encapsulate transaction and batcher.

**Comment by arsulegai** [comment]
@Kaixinguoer210 that'll be a client application in go language.

There were many requests for writing a client application using sawtooth go sdk, I am working on merging this code. For time being you may find working code for intkey-go in my repository https://github.com/arsulegai/sawtooth-sdk-go/tree/intkey_go_client/examples/intkey_go/src/sawtooth_intkey_client also there's a PR raised on sawtooth-core repository for documenting how to build a client in go.

**Comment by Kaixinguoer210** [comment]
@arsulegai Thank you very much. I will check it again.
