### ISSUE TITLE
Migrate sdk from core project

### ISSUE THREAD

**Issue by danielcooperxyz** [hyperledger/sawtooth-sdk-go#2]
Are there any plans to do this?

**Comment by boydjohnson** [comment]
https://jira.hyperledger.org/browse/STL-974 Hi, @danielcooperxyz This jira story explains what is being done.

**Comment by danielcooperxyz** [comment]
That's great thank you for the information.

For any one else interested I have used https://github.com/rberg2/sawtooth-go-sdk for the time being as it is available at the moment but is **only a test**.

I have not been able to build it on Windows for the moment, but using [this](https://gist.github.com/danielcooperxyz/bda847cc6e663355baae00a41e7ae1e8) Dockerfile I can get and compile the sdk.
